### ISSUE TITLE
Multiple LD2450s on one ESP? 

### ISSUE THREAD

**Issue by Aaroneisele55** [uncle-yura/esphome-ld2450#5]
Hello,
I would like to know if it's possible to use your component for more than one LD2450 on the same Esp32, and if yes, how.

Best regards

Aaron

**Comment by uncle-yura** [comment]
I have not checked how such a configuration works on hardware, but I think it is possible.
You can add a separate UART port and make a complete duplicate of the configuration for the second sensor.
Something like this:
```
uart:
  - id: uart_bus_1
    tx_pin: 
      number: GPIO1
    rx_pin: 
      number: GPIO3
    baud_rate: 256000
    parity: NONE
    stop_bits: 1

  - id: uart_bus_2
    tx_pin: 
      number: uart_2_tx_pin
    rx_pin: 
      number: uart_2_rx_pin
    baud_rate: 256000
    parity: NONE
    stop_bits: 1

ld2450:
  - uart_id: uart_bus_1
    id: ld2450_1
    update_interval: 100ms
    invert_y: true
    invert_x: true

  - uart_id: uart_bus_2
    id: ld2450_2
    update_interval: 100ms
    invert_y: true
    invert_x: true

binary_sensor:
  - platform: ld2450
    ld2450_id: ld2450_1
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target
```
