### ISSUE TITLE
Set Custom Presence Region

### ISSUE THREAD

**Issue by memehammad** [uncle-yura/esphome-ld2450#6]
Hey, 
I'm quite stupid so I cant figure out how to use custom presence regions. I'd like to split up my room into multiple zones and use the ld2450 to detect and tell home assistant which one I'm in. How would I go about achieving this?

**Comment by uncle-yura** [comment]
1. Custom regions work with already processed coordinates, so first you need to adjust the rotation and inversion if necessary. In this [post](https://community.home-assistant.io/t/hlk-ld2450-initial-experiments-to-connect-to-homeassistant/578878/351), I wrote the action algorithm and added widgets for visualizing the coordinates.
2. When you have made a visualization and the found person is moving in the correct coordinates, you need to add presence zones to the firmware
```
...
number:
- platform: ld2450
  presence_regions:
    - x0: -20
      y0: 90
      x1: 80
      y1: 190
      id: presence_region_0
    - x0: 80
      y0: 90
      x1: 180
      y1: 240
      id: presence_region_1
...
```
3. After adding presence zones, add binary sensors, they will be exported and HomeAssistant will know in which zone a person is.
```
...
binary_sensor:
- platform: ld2450
  presence_regions:
    - name: "Region 0 Presence"
      region_id: presence_region_0
    - name: "Region 1 Presence"
      region_id: presence_region_1
    - name: "Region 2 Presence"
      region_id: presence_region_2
    - name: "Region 3 Presence"
      region_id: presence_region_3
    - name: "Region 4 Presence"
      region_id: presence_region_4
...
```
